# Generated by Django 6.0.3 on 2026-03-28 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ambulance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=100)),
                ("latitude", models.FloatField(default=0)),
                ("longitude", models.FloatField(default=0)),
                ("contact", models.CharField(blank=True, default="", max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=100)),
                ("latitude", models.FloatField(default=0)),
                ("longitude", models.FloatField(default=0)),
                ("contact", models.CharField(blank=True, default="", max_length=15)),
                ("antivenom", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("victim", "Victim"),
                            ("driver", "Ambulance Driver"),
                            ("volunteer", "Volunteer"),
                            ("hospital", "Hospital"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("password", models.CharField(blank=True, default="", max_length=100)),
                ("contact", models.CharField(blank=True, default="", max_length=15)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "eme_contact",
                    models.CharField(blank=True, default="", max_length=15),
                ),
            ],
        ),
        migrations.CreateModel(
            name="volunteer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=100)),
                ("latitude", models.FloatField(default=0)),
                ("longitude", models.FloatField(default=0)),
                ("contact", models.CharField(blank=True, default="", max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="EmergencyAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(blank=True, max_length=100)),
                ("patient_phone", models.CharField(blank=True, max_length=15)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("snake_type", models.CharField(blank=True, max_length=100)),
                ("has_vehicle", models.BooleanField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("hospital_routed", "Hospital Routed"),
                            ("ambulance_notified", "Ambulance Notified"),
                            ("ambulance_accepted", "Ambulance Accepted"),
                            ("volunteer_notified", "Volunteer Notified"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("driver_attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("driver_notified_at", models.DateTimeField(blank=True, null=True)),
                ("attempted_driver_ids", models.JSONField(blank=True, default=list)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.ambulance",
                    ),
                ),
                (
                    "assigned_hospital",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.hospital",
                    ),
                ),
                (
                    "assigned_volunteer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.volunteer",
                    ),
                ),
            ],
        ),
    ]
