# Generated by Django 6.0.3 on 2026-03-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_ambulance_email_ambulance_password_volunteer_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ambulance",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="emergencyalert",
            name="antivenom_confirmed",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emergencyalert",
            name="assigned_hospital_latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emergencyalert",
            name="assigned_hospital_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emergencyalert",
            name="hospital_attempt_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="emergencyalert",
            name="hospital_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
