# Generated by Django 6.0.3 on 2026-03-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_ambulance_is_available_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ambulance",
            name="latitude",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="ambulance",
            name="longitude",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="latitude",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="longitude",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="latitude",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="longitude",
            field=models.FloatField(blank=True, default=0),
        ),
    ]
